// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywfeftctorzgsestierp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3ZmVmdGN0b3J6Z3Nlc3RpZXJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDQwNTAsImV4cCI6MjA2NTIyMDA1MH0.6x4UmVHgxu_3TfTczUpwX0lFnLkz8YE0DkqLOuuseFE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);